spring:
  datasource:
    password: MI21mi0933
    url: jdbc:mysql://localhost:3306/booksdb
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
